version: '2.1'

services:

  users-db:
    container_name: users-db
    build: https://github.com/SamR1/tuto-microservices.git#master:flask-microservices-users/project/db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    build: https://github.com/SamR1/tuto-microservices.git#master:flask-microservices-users/
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db

  web-service:
    container_name: web-service
    build: https://github.com/SamR1/tuto-microservices.git#master:flask-microservices-client/
    ports:
      - '3007:3000' # expose ports - HOST:CONTAINER
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      users-service:
        condition: service_started
    links:
      - users-service